// GENERATED by `python -m trd.brand --sync` from apps/web/src/styles/tokens.css + theme-handoff.css — do not edit.
// Brand colours for pdf-lib (the Form 50-114 audit page). Values are 0–1 RGB triples.

export const THEME = "handoff";
export const BRAND_NAME = "Clean Bill";
export const SITE = "https://cleanbillco.com";

export const HEX = {
  "bg": "#F7FAFA",
  "surface": "#FFFFFF",
  "ink": "#172026",
  "body": "#33454D",
  "muted": "#5A6B72",
  "placeholder": "#8A9AA1",
  "primary": "#157A8A",
  "primary-strong": "#0E5661",
  "primary-tint": "#E6F3F5",
  "primary-soft": "#7FC4CF",
  "on-primary": "#FFFFFF",
  "dark": "#0F3A44",
  "on-dark": "#C7DCE0",
  "on-dark-strong": "#FFFFFF",
  "accent": "#F2E9DA",
  "accent-text": "#6B4E1E",
  "accent-body": "#5A4A33",
  "amount": "#0E5661",
  "line": "#D4E0E3",
  "hairline": "#E1EAEC",
  "row-tint": "#F1F6F7",
  "success": "#1E7B4F",
  "success-bg": "#E3F3EA",
  "error": "#B4453A",
  "error-bg": "#FBF3F2",
  "disabled": "#9FC7CE",
} as const;

export const RGB: Record<keyof typeof HEX, [number, number, number]> = {
  "bg": [0.9686, 0.9804, 0.9804],
  "surface": [1.0000, 1.0000, 1.0000],
  "ink": [0.0902, 0.1255, 0.1490],
  "body": [0.2000, 0.2706, 0.3020],
  "muted": [0.3529, 0.4196, 0.4471],
  "placeholder": [0.5412, 0.6039, 0.6314],
  "primary": [0.0824, 0.4784, 0.5412],
  "primary-strong": [0.0549, 0.3373, 0.3804],
  "primary-tint": [0.9020, 0.9529, 0.9608],
  "primary-soft": [0.4980, 0.7686, 0.8118],
  "on-primary": [1.0000, 1.0000, 1.0000],
  "dark": [0.0588, 0.2275, 0.2667],
  "on-dark": [0.7804, 0.8627, 0.8784],
  "on-dark-strong": [1.0000, 1.0000, 1.0000],
  "accent": [0.9490, 0.9137, 0.8549],
  "accent-text": [0.4196, 0.3059, 0.1176],
  "accent-body": [0.3529, 0.2902, 0.2000],
  "amount": [0.0549, 0.3373, 0.3804],
  "line": [0.8314, 0.8784, 0.8902],
  "hairline": [0.8824, 0.9176, 0.9255],
  "row-tint": [0.9451, 0.9647, 0.9686],
  "success": [0.1176, 0.4824, 0.3098],
  "success-bg": [0.8902, 0.9529, 0.9176],
  "error": [0.7059, 0.2706, 0.2275],
  "error-bg": [0.9843, 0.9529, 0.9490],
  "disabled": [0.6235, 0.7804, 0.8078],
};

/** The mark (a receipt outline with a check) as SVG path data in a 100 × 100 box; stroke it, do not fill it. */
export const MARK_PATH = "M 22 8 L 78 8 L 78 92 L 69 84 L 60 92 L 51 84 L 42 92 L 33 84 L 22 92 L 22 8 M 34 30 L 54 30 M 34 44 L 48 44 M 38 64 L 48 74 L 68 52";
export const MARK_STROKE = 8;
