// GENERATED by `python -m trd.brand --sync` from apps/web/src/styles/tokens.css + theme-handoff.css — do not edit.
// The few brand values the web app needs outside CSS. Everything else is a CSS token (src/styles/tokens.css).

export const THEME = "handoff";
export const THEME_COLOR = "#F7FAFA";   // <meta name="theme-color">: the page background of the default theme
export const BRAND_HEX = { primary: "#157A8A", ink: "#172026", bg: "#F7FAFA" } as const;
/** The mark (a receipt outline with a check) as SVG path data in a 100 × 100 box; stroke it with currentColor. */
export const MARK_PATH = "M 22 8 L 78 8 L 78 92 L 69 84 L 60 92 L 51 84 L 42 92 L 33 84 L 22 92 L 22 8 M 34 30 L 54 30 M 34 44 L 48 44 M 38 64 L 48 74 L 68 52";
export const MARK_STROKE = 8;
