"""Tax rates and exemption rules per Travis County taxing unit and tax year — loaded from rates/units.json.

units.json is generated by `python -m trd.estimator.build_units` from public sources (the county's truth-in-taxation
rate summary, TCAD's exemption listing, and a cross-check against the certified roll); see that module's docstring for
the confirmation rule. Each unit is keyed by TCAD's entity code (the same code PROP_ENT and property_entities use):

  "01": {"name": "AUSTIN ISD", "type": "isd", "alias": "AISD", "taxing": true, "ceiling": true,
         "years": {"2025": {"rate": 0.9252, "rate_confirmed": true, "hs": {"amount": 140000, "pct": 0.0, "min": 0},
                            "hs_confirmed": true, "ov65": 85000, "ov65_confirmed": false, "ceiling": true, ...}}}

Rates are per $100 of taxable value. HS exemption for a value V = min(V, amount + (max(pct*V, min) if pct else 0)) —
school districts get the state amount plus any local-option percentage; local units are percentage-with-minimum or a
flat amount. OV65 is a flat amount that stacks on top of HS.

Glossary: HS — general residence homestead exemption · OV65 — additional exemption for owners 65+ · pct — a
percentage-of-value exemption (§11.13(n)), $5,000 minimum · ceiling — the unit freezes the 65+ owner's tax.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

UNITS_PATH = Path(__file__).parent / "rates" / "units.json"
TAX_YEARS = (2024, 2025)  # years with an adopted rate for every unit; 2026 rates arrive Sep-Oct (G-31)

# The five units on a City-of-Austin / Austin ISD bill — the prototype's default when a property's units are unknown.
DEFAULT_UNITS = ("01", "02", "03", "68", "2J")


@lru_cache(maxsize=1)
def load_units() -> dict:
    return json.loads(UNITS_PATH.read_text())


def units() -> dict[str, dict]:
    return load_units()["units"]


def unit(cd: str) -> dict | None:
    return units().get(cd)


def unit_key(cd: str) -> str:
    """Key used in estimator output: the alias for the five well-known units (AISD, CITY, ...), else the entity code."""
    u = unit(cd)
    return (u or {}).get("alias") or cd


def unit_name(cd: str) -> str:
    u = unit(cd)
    return (u or {}).get("name") or cd


def year_rule(cd: str, year: int) -> dict | None:
    u = unit(cd)
    return (u or {}).get("years", {}).get(str(year))


def taxing_units(codes) -> list[str]:
    """Keep only codes that levy an ad valorem rate (drops the appraisal district, PIDs, TIRZs, unknown codes)."""
    return [c for c in codes if (unit(c) or {}).get("taxing")]


# Legacy view for code written against the prototype's five-unit table: {alias: {...}} with the old field names.
def _legacy_entities() -> dict:
    out = {}
    for cd in DEFAULT_UNITS:
        u = unit(cd); ys = u["years"]
        out[u["alias"]] = {
            "name": u["name"], "entity_cd": cd,
            "rate": {y: ys[str(y)]["rate"] for y in TAX_YEARS},
            "hs": {y: ys[str(y)]["hs"] for y in TAX_YEARS},
            "ov65": {y: ys[str(y)]["ov65"] for y in TAX_YEARS},
            "ceiling": u["ceiling"],
            "confirmed": {"rate": all(ys[str(y)]["rate_confirmed"] for y in TAX_YEARS), "hs": all(ys[str(y)]["hs_confirmed"] for y in TAX_YEARS),
                          "ov65": all(ys[str(y)]["ov65_confirmed"] for y in TAX_YEARS)},
            "source": ys[str(TAX_YEARS[-1])]["hs_basis"],
        }
    return out


class _LazyEntities(dict):
    def __getitem__(self, k):
        if not dict.__len__(self): self.update(_legacy_entities())
        return dict.__getitem__(self, k)
    def items(self):
        if not dict.__len__(self): self.update(_legacy_entities())
        return dict.items(self)
    def __iter__(self):
        if not dict.__len__(self): self.update(_legacy_entities())
        return dict.__iter__(self)


ENTITIES = _LazyEntities()

# TCAD's published benchmark used as a sanity check in tests:
# "In 2025, having a homestead exemption saved the average Travis County property owner $3,663."
# (traviscad.org news, Jan 2026). That figure includes the 10% appraisal-cap effect on long-held homes,
# which this estimator deliberately excludes for late filers.
TCAD_AVG_HS_SAVINGS_2025 = 3_663
